name: chatdrop
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  permission_handler: ^11.0.1
  on_audio_query: ^2.9.0
  get: ^4.6.6
  just_audio: ^0.9.35
  fading_edge_scrollview: ^4.0.0
  audio_service: ^0.18.12
  get_it: ^7.6.4
  syncfusion_flutter_gauges: ^24.1.41
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  path_provider: ^2.1.1
  external_path: ^1.0.3
  provider: ^6.1.1
  firebase_core: ^2.2.0
  firebase_auth: ^4.1.3
  google_sign_in: ^6.1.6
  cloud_firestore: ^4.13.6
  image_picker: ^1.0.5
  firebase_storage: ^11.5.6
  firebase_messaging: ^14.7.9
  http: ^0.13.5
  flutter_notification_channel: ^2.0.0
  gallery_saver: ^2.3.2
  firebase_analytics: ^10.7.4
  firebase_app_check: ^0.2.1+8
  cloud_functions: ^4.5.8
  firebase_crashlytics: ^3.4.8
  firebase_dynamic_links: ^5.4.8
  firebase_in_app_messaging: ^0.7.4+8
  firebase_app_installations: ^0.2.4+8
  firebase_ml_model_downloader: ^0.2.4+8
  firebase_performance: ^0.9.3+8
  firebase_database: ^10.3.8
  firebase_remote_config: ^4.3.8
  emoji_picker_flutter: ^1.6.3
  html: ^0.15.4
  flutter_svg: ^1.0.0
  audio_video_progress_bar: ^2.0.1
  dart_des: ^1.0.2
  eva_icons_flutter: ^3.1.0
  go_router: ^13.0.0
  iconsax: ^0.0.8
  sliding_up_panel: ^2.0.0+1
  duration_picker: ^1.1.1
  flutter_displaymode: ^0.6.0
  flutter_swipe_action_cell: ^3.1.2
  flutter_colorpicker: ^1.0.3
  dropdown_button2: ^2.3.9
  dynamic_color: ^1.6.5
  flutter_lyric: ^2.0.4+6
  flip_card: ^0.7.0
  flutter_progress_status: ^0.0.3
  youtube_explode_dart: ^1.12.4
  auto_size_text: ^3.0.0
  skeletons: ^0.0.3
  country_picker: ^2.0.20
  shared_preferences: ^2.2.0
  url_launcher: ^6.1.14
  just_audio_mpv: ^0.1.7
  palette_generator: ^0.3.3+3
  metadata_god: ^0.5.2+1
  google_fonts: ^4.0.4
  logging: ^1.2.0
  intl: ^0.18.1
  bitsdojo_window: ^0.1.5
  chewie: ^1.5.0
  flutter_localization: ^0.2.0
  titlebar_buttons: ^1.0.0
  device_info_plus: ^8.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/img/
    - assets/video/
  fonts:
    - family: Tilt Neon
      fonts:
        - asset: assets/fonts/TiltNeon-Regular.ttf
    - family: tkdmusicfluttericon
      fonts:
        - asset: assets/fonts/tkdmusicfluttericon.ttf
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
flutter_intl:
  enabled: true

# flutter_launcher_icons:
#   image_path: "assets/img/app_logo.png"

#   android: "launcher_icon"
#   min_sdk_android: 21
#   adaptive_icon_background: "#00000000"
#   icon_path_android: "assets/img/app_logo.png"
#   # adaptive_icon_foreground: "assets/icon/foreground.png"

#   ios: true
#   icon_path_ios: "assets/img/app_logo.png"
#   remove_alpha_channel_ios: true

#   web:
#     generate: true
#     image_path: "assets/img/app_logo.png"
#     background_color: "#00000000"
#     theme_color: "#00000000"

#   windows:
#     generate: true
#     image_path: "assets/img/app_logo.png"
#     icon_size: 48

#   macos:
#     generate: true
#     image_path: "assets/img/app_logo.png"
